name: Deno Format

on:
  push:
    branches:
      - main

jobs:
  format:
    name: Run Deno fmt
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Deno 2.1
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.1

      # Run deno fmt and check for changes
      - name: Format Code
        run: deno task format

      # Commit changes if any
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "chore: ✏️ Format code"
            git push
          fi
